### ISSUE TITLE
Suggestion - externalize format property

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/presentation-exchange#228] opened 2021-06-29 16:28 UTC
Format element is not credential or presentation specific, it is a static information that applies to all the credentials and presentations that the verifier requests and holder can handle. It would be preferable to exchange such information prior to the interaction rather than passing it inside the request.

Including such metadata (like formats in this case) inside the request would be an unexpected behavior for the parties in some transport protocols, like OpenID Connect, where there is an established process to exchange metadata between verifier and holder (process called Registration and Discovery).

Again, the goal is not to break PE, but to get closer to the goal of making it protocol agnostic by reflecting differences in structures across various transport protocols.

**Comment by csuwildcat** [comment] 2021-06-29 18:00
@Sakurann there are a couple issue here:

1. All other envelope protocols besides SIOP need the `format` property/values for this purpose, so if we removed it, they would not have what they need to facilitate exchanges.
2. If the proposal was not to remove it from the spec, but instead change the spec to state "The `format` property will live somewhere different in every envelope that uses PE, and may be called by a different name', or that "The `format` property will live in Place X for Protocol A, Place Y for Protocol B, and Place Z for Protocol C", that is exactly what PE was designed to eliminate, and would create a bunch of different code paths.

I think you'll find folks are far more amenable to changing things *within* the PE objects/values, than moving them to per-protocol special locations, as the latter breaks the intent of the spec.

**Comment by David-Chadwick** [comment] 2021-06-29 19:14
@csuwildcat So what you are effectively saying is that every protocol that already has its own defined way of specifying transfer formats should disregard it and use some externally defined method instead. 
This is hardly a good way of getting existing protocols to support your approach. Rather your alternative (disliked) proposal for a spec change in 2. would surely be a better way of getting the protocols to buy into PE. Let PE specify WHAT is required in terms of claims, and let the protocol specify HOW it is transferred. If incompatible formats are specified in the OIDC meta data of the RP and SIOP then there is little point in even making a PE request for VCs as the RP knows before it starts that the exchange will be impossible.

**Comment by csuwildcat** [comment] 2021-06-29 22:35
@David-Chadwick perhaps there is a misunderstanding about the `format` property in PE: it is not declaring transfer formats of wrapper objects or any other transport-level detail, it is telling the Holder exactly which credential formats they must be holding to successfully match what the Verifier can process. I will again also note that the format of a credential a Holder is holding is definitely a WHAT of the credential, not a HOW - you can test this by simply using the words in a sentence:

WHAT: "The `format` property tells the Holder WHAT credential formats/sig schemes the Verifier can process, so the Holder can know if they are holding WHAT is required."

HOW: "The `format` property tells the Holder HOW credential formats/sig schemes the Verifier can process, so the Holder can know if they are holding HOW is required."

^ very clearly a WHAT, not a HOW

**Comment by David-Chadwick** [comment] 2021-06-30 08:29
@csuwildcat At the application level, the RP/SP manager is interested in subject properties. The WHAT. E.g. In order to enter this nightclub I need to see your date of birth from your drivers license. The application level is not interested in HOW these attributes are packaged up, transferred and cryptographically protected. The manager is unlikely to say that you cannot enter this nightclub because your properties were transferred using DIDComm and signed by an LD-Proof, but you can if you present an mDL using OIDC. (But the software he buys from one supplier might have this constraint). How the packaging and transfer are done are all formatting information. So is the cryptographic protection mechanism. The crypto does not say WHAT is being transferrred, it says HOW it is being protected. So to rephrase your sentences

HOW: "The format property tells the Holder HOW the credential claims should be formatted and cryptographically protected so that the Verifier can process them, so that the Holder can know if the Verifier is able to process them."

WHAT. "The claims requirements tell the Holder WHAT is required in terms of subject properties and selective disclosures. This is independent of HOW these claims are formatted and cryptographically protected".

One can imagine a VC Issuer that is capable of packaging the same claims in different ways with different crypto mechanisms, so that their Holders are able to respond to many different types of HOW requests (with the same WHAT requirements)

**Comment by Sakurann** [comment] 2021-06-30 17:50
Maybe "externalize" was a confusing word.

Since `format` is already optional in PE, some protocols sending it not inside `presentation_definition` should be no problem. For example OIDC sending that information in Registration/Discovery process.

So, technically PE v1 as-is satisfies the need of OIDC, and if people agree, I am ok closing this issue. 
Optionally, we could add a text saying that 
> "message-based protocols can use `format` property inside `presentation_definition` while server-client protocols (not sure this is the best description) can use other mechanisms to communicate format inf among themselves."

**Comment by csuwildcat** [comment] 2021-07-01 19:21
I think we can probably make this a component that can be located either in the single object or elsewhere, if a transport protocol needs the flexibility. As long as the format object (wherever it lives) is fed into PE's deterministic evaluation function/steps, it will the PE implementation code and outcome will be virtually identical.

**Comment by Sakurann** [comment] 2021-07-29 03:28
ok, great, would you be ok with me doing a PR adding a text saying something along the lines of "optional components are not required to be included in the PE and can be included in the 'transport protocol' outside of PE, as specified by the respective 'transport protocol' "?

**Comment by brentzundel** [comment] 2021-07-29 17:02
slight re-wording that I'd be fine with, "optional PE components MAY be be included in the 'transport protocol' rather than inside the PE object, as specified by the respective 'transport protocol', provided the 'transport protocol' also describes how to re-incorporate the components into the PE object prior to PE processing."

**Comment by OR13** [comment] 2021-07-29 17:17
Proposed language:

Implementers MUST support the normative data model and processing requirements, however, implementers MAY rely on transport specific intermediate representations, so long as they do not impose processing requirements on intermediate representations that are not normatively defined in the PE spec.

**Comment by tlodderstedt** [comment] 2021-08-03 12:32
I think there is a need for formats at two different levels:

1. capabilities: what format are verifiers/holders able to process
2. credential constraints: what format expects a verifier a certain credential to be represented in. 

(1) can be represented in OIDC using client/OP metadata or the way PE defines it 
(2) is missing in PE - it is however very important since it influences the way paths are defined, e.g. $.credentialSubject.account[*].id seems to be a path within a JSON-LD-based credential whereas $.vc.credentialSubject.account[*].id seems to be referring to an element within a JWT-based credential. Using them in parallel in constraints (see https://identity.foundation/presentation-exchange/#input-descriptor) to me seems like a very error prone reference mechanism.

I think adding format on the level of the input_descriptor would improve PE's robustness significantly.

**Comment by csuwildcat** [comment] 2021-09-09 17:57
ACTION ITEM: We will externalize the top-level format property and change the spec text to reflect that it may live elsewhere prior to evaluation of candidate credentials.

**Closed** 2022-05-19 17:53 UTC
