### ISSUE TITLE
Optional constraint fields

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/presentation-exchange#377] opened 2022-09-30 16:00 UTC
Is there any way other than using `submission_requirements` to support an optional field? e.g. middleName. Include it if you have it. It’d be somewhat unfortunate if optional fields aren’t supported in a way aside from using `submission_requirements` wherein two `input_descriptor` objects are provided for the same group and only 1 must be satisfied. 1 input_descriptor would include the optional field in its fields array and 1 would exclude it… thus creating support for optional fields (albeit janky and verbose)

**Comment by csuwildcat** [comment] 2022-09-30 17:41
@dtmcg @brentzundel @kimdhamilton I really think this is a necessary addition, and is backwards compatible.

**Comment by kimdhamilton** [comment] 2022-10-02 02:35
yes, this makes sense. I wonder if we can reuse the required/preferred pattern here, and have required be default. Although I need to refresh my memory on whether that's applicable here

**Comment by csuwildcat** [comment] 2022-10-02 03:49
The default is already 'required' without any property, so if we did
`optional: true` it would be a gracefully upgrading addition.

**Comment by brentzundel** [comment] 2022-10-17 21:12
is this a duplicate of #375 ?

**Comment by csuwildcat** [comment] 2022-10-17 23:19
Yes, it's a dupe, and the PR closed both

**Comment by brentzundel** [comment] 2022-10-20 16:47
addressed by #378

**Closed by brentzundel** 2022-10-20 16:47 UTC
