### ISSUE TITLE
Converge the multiple active draft verified claims request specs that have similar goals

### ISSUE THREAD

**Issue by selfissued** [decentralized-identity/presentation-exchange#36] opened 2020-07-06 05:04 UTC
The industry will be best served to have a unified verified claims request spec that works at least for those represented in JSON, such W3C Verifiable Credentials and OpenID Connect for Identity Assurance JWTs.  We should actively work on converging this specification with at least these others:

- eKYC-IDA claims request format https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html#name-requesting-verified-claims
- Edmund Jay's and Nat Sakimura's claims aggregation request spec https://bitbucket.org/edmund_jay/oidc-claims-aggregation/src/master/OpenID%20Connect%20Claims%20Aggregation.md

For extra credit, consider how to extend the verified claims request syntax to also support CBOR.

**Comment by kimdhamilton** [comment] 2022-02-10 05:08
to discuss Feb 10 2022: ok to close?

**Comment by kimdhamilton** [comment] 2022-02-10 18:26
@selfissued we're proposing to close this as not actionable if no updates/clarifications by Feb 24

**Comment by csuwildcat** [comment] 2022-04-21 17:46
Closing after period of commentary has passed without actionable info. Note: PE unifies all of these by addressing all their use cases without hard bindings to any one of them. It would behoove the community to circle the wagons around this spec as the solution that covers them all (by design)

**Closed by csuwildcat** 2022-04-21 17:46 UTC
Labels: convergence, pending-close
