### ISSUE TITLE
What does PE look like within OpenID Connect?

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#101] opened 2020-09-03 17:46 UTC
https://github.com/decentralized-identity/presentation-exchange/issues/96

@glcohen @pamelatech if you have OpenID interoperability examples, we would really appreciate them.

**Comment by timcappalli** [comment] 2020-09-16 22:35
`{
  "response_type": "id_token",
  "response_mode": "form_post",
  "client_id": "https://myrp.net/request",
  "redirect_uri": "https://myrp.net/verify",
  "scope": "openid did_authn",
  "state": "ao8kdI_WHrA5Qw",
  "nonce": "sJQObHuzkjZ2FA",
  "iss": "did:ion:EiD9lDdWcAGXJDaUbPSlW94feOUl7ipcbIg6maBjwg2lUg",
  "registration": {
    "client_name": "Decentralized Identity Team",
    "client_purpose": "Give us this information please (with cherry on top)!",
    "tos_uri": "https://myrp.net/tos.html",
    "logo_uri": "https://myrp.net/images/did_logo.png"
  },
  "iat": 1600295643,
  "exp": 1600295943,
  "presentation_definition": {
    "input_descriptors": [
      {
        "id": "IdentityCardCredential",
        "schema": {
          "uri": [
            "IdentityCardCredential"
          ],
          "name": "Decentralized Identity Team",
          "purpose": "Give us this information please (with cherry on top)!"
        },
        "issuance": [
          {
            "manifest": "https://portableidentitycards.azure-api.net/dev-v1.0/536279f6-15cc-45f2-be2d-61e352b51eef/portableIdentities/contracts/IdentityCard"
          }
        ]
      }
    ],
    "name": "Decentralized Identity Team",
    "purpose": "Give us this information please (with cherry on top)!"
  }
}`

**Comment by kimdhamilton** [comment] 2021-10-06 21:53
to discuss 10/7: is this different from #92 ?

FYI @csuwildcat @brentzundel

**Comment by kimdhamilton** [comment] 2021-10-07 17:32
dupe of #92

**Closed by kimdhamilton** 2021-10-07 17:32 UTC
Labels: needs discussion
