### ISSUE TITLE
Presentation Submission Blob Decoding

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#32] opened 2020-07-02 16:52 UTC
Add language talking about how to decode JWTs, Base64, etc. upon their encounter within the Presentation Submission. Is this normative or non-normative, and why?

**Comment by csuwildcat** [comment] 2020-07-16 16:48
Dupe of https://github.com/decentralized-identity/presentation-exchange/issues/15

**Closed by csuwildcat** 2020-07-16 16:49 UTC
